<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SubCriteria;

class SubCriteriaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $subs = [
            [
                'criteria_id' => '1',
                'umur' => '-',
                'sub_criteria' => '> 4 s/d <= 5 Tahun',
                'range' => '-',
                'bobot' => '4',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '1',
                'umur' => '-',
                'sub_criteria' => '> 3 s/d <= 4 Tahun',
                'range' => '-',
                'bobot' => '4',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '1',
                'umur' => '-',
                'sub_criteria' => '> 2 s/d <= 3 Tahun',
                'range' => '-',
                'bobot' => '5',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '1',
                'umur' => '-',
                'sub_criteria' => ' 1 s/d 2 Tahun',
                'range' => '-',
                'bobot' => '5',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '2',
                'umur' => '1 Tahun',
                'sub_criteria' => 'Kurus',
                'range' => '< 7.7 Kg',
                'bobot' => '5',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '2',
                'umur' => '1 Tahun',
                'sub_criteria' => 'Normal (Ideal)',
                'range' => '7.7 s/d 11 Kg',
                'bobot' => '4',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '2',
                'umur' => '1 Tahun',
                'sub_criteria' => 'Kegemukan (Obesitas)',
                'range' => '> 11 Kg',
                'bobot' => '3',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '2',
                'umur' => '2 Tahun',
                'sub_criteria' => 'Kurus',
                'range' => '< 9.7 Kg',
                'bobot' => '5',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '2',
                'umur' => '2 Tahun',
                'sub_criteria' => 'Normal (Ideal)',
                'range' => '9.7 s/d 15 Kg',
                'bobot' => '4',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '2',
                'umur' => '2 Tahun',
                'sub_criteria' => 'Kegemukan (Obesitas)',
                'range' => '> 15 Kg',
                'bobot' => '3',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],

            [
                'criteria_id' => '2',
                'umur' => '3 Tahun',
                'sub_criteria' => 'Kurus',
                'range' => '< 11.3 Kg',
                'bobot' => '5',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '2',
                'umur' => '3 Tahun',
                'sub_criteria' => 'Normal (Ideal)',
                'range' => '11.3 s/d 18.3 Kg',
                'bobot' => '4',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '2',
                'umur' => '3 Tahun',
                'sub_criteria' => 'Kegemukan (Obesitas)',
                'range' => '> 18.3 Kg',
                'bobot' => '3',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],

            [
                'criteria_id' => '2',
                'umur' => '4 Tahun',
                'sub_criteria' => 'Kurus',
                'range' => '< 12.7 Kg',
                'bobot' => '5',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '2',
                'umur' => '4 Tahun',
                'sub_criteria' => 'Normal (Ideal)',
                'range' => '12.7 s/d 21.2 Kg',
                'bobot' => '4',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '2',
                'umur' => '4 Tahun',
                'sub_criteria' => 'Kegemukan (Obesitas)',
                'range' => '> 21.2 Kg',
                'bobot' => '3',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],

            [
                'criteria_id' => '2',
                'umur' => '5 Tahun',
                'sub_criteria' => 'Kurus',
                'range' => '< 14.1 Kg',
                'bobot' => '5',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '2',
                'umur' => '5 Tahun',
                'sub_criteria' => 'Normal (Ideal)',
                'range' => '14.1 s/d 24.2 Kg',
                'bobot' => '4',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '2',
                'umur' => '5 Tahun',
                'sub_criteria' => 'Kegemukan (Obesitas)',
                'range' => '> 24.2 Kg',
                'bobot' => '3',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '3',
                'umur' => '1 Tahun',
                'sub_criteria' => 'Tinggi',
                'range' => '> 90 cm',
                'bobot' => '3',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '3',
                'umur' => '1 Tahun',
                'sub_criteria' => 'Normal',
                'range' => '< 90 s/d 87 cm',
                'bobot' => '4',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '3',
                'umur' => '1 Tahun',
                'sub_criteria' => 'Pendek',
                'range' => '< 87 cm cm',
                'bobot' => '5',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '3',
                'umur' => '2 Tahun',
                'sub_criteria' => 'Tinggi',
                'range' => '> 90 cm',
                'bobot' => '3',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '3',
                'umur' => '2 Tahun',
                'sub_criteria' => 'Normal',
                'range' => '< 90 s/d 87 cm',
                'bobot' => '4',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '3',
                'umur' => '2 Tahun',
                'sub_criteria' => 'Pendek',
                'range' => '< 87 cm cm',
                'bobot' => '5',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '3',
                'umur' => '3 Tahun',
                'sub_criteria' => 'Tinggi',
                'range' => '> 90 cm',
                'bobot' => '3',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '3',
                'umur' => '3 Tahun',
                'sub_criteria' => 'Normal',
                'range' => '< 90 s/d 87 cm',
                'bobot' => '4',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '3',
                'umur' => '3 Tahun',
                'sub_criteria' => 'Pendek',
                'range' => '< 87 cm cm',
                'bobot' => '5',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '3',
                'umur' => '4 Tahun',
                'sub_criteria' => 'Tinggi',
                'range' => '> 90 cm',
                'bobot' => '3',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '3',
                'umur' => '4 Tahun',
                'sub_criteria' => 'Normal',
                'range' => '< 90 s/d 87 cm',
                'bobot' => '4',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '3',
                'umur' => '4 Tahun',
                'sub_criteria' => 'Pendek',
                'range' => '< 87 cm cm',
                'bobot' => '5',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '3',
                'umur' => '5 Tahun',
                'sub_criteria' => 'Tinggi',
                'range' => '> 90 cm',
                'bobot' => '3',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '3',
                'umur' => '5 Tahun',
                'sub_criteria' => 'Normal',
                'range' => '< 90 s/d 87 cm',
                'bobot' => '4',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '3',
                'umur' => '5 Tahun',
                'sub_criteria' => 'Pendek',
                'range' => '< 87 cm cm',
                'bobot' => '5',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '4',
                'umur' => '-',
                'sub_criteria' => 'Ada',
                'range' => '-',
                'bobot' => '5',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'criteria_id' => '4',
                'umur' => '-',
                'sub_criteria' => 'Tidak Ada',
                'range' => '-',
                'bobot' => '4',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
        ];

        SubCriteria::insert($subs);
    }
}
